baseURL = 'https://wolfpackcycling.org/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'Wolf Pack Cycling Club'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  # name = "Your name here"
  # headline = "An awesome person"
  # image = "img/author.jpg"  # path relative to static directory
  
  headline = "Wolf Pack Cycling is a Southern California based cycling team dedicated to furthering the sport of cycling. The team members share a passion for cycling and a desire for the camaraderie that the team provides. Wolf Pack’s riders are experienced, accomplished cyclists who participate in a variety of disciplines including, road, criterium, mountain, and track cycling. The team is proud of its dedication to cycling and grateful to the sponsors that have chosen to partner with us."

  # image = "img/wolfpack-logo-orange-black.jpg"

  # background: #012535
  image = "img/wolfpack-wolf-logo.jpg"
  

  links = [
    # actual links here (keep defaults below, commented out)

    { strava = { href = "https://www.strava.com/clubs/4183/discussion?num_entries=10", text = "Strava" } },
    { instagram = "https://www.instagram.com/wolfpackcycling.sandiego/" },
    { facebook = "https://www.facebook.com/wolfpackcycling" },
    { twitter = "https://twitter.com/WolfPack_WPC" },

    # { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
